# Generated by Django 5.0.6 on 2024-07-05 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True


    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('rowstatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('locationname', models.CharField(max_length=255)),
                ('locationaddress', models.TextField()),
                ('createduser', models.CharField(max_length=100)),
                ('modifieduser', models.CharField(max_length=100)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('rowstatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productcode', models.CharField(max_length=100)),
                ('qrcode', models.TextField()),
                ('productname', models.CharField(max_length=255)),
                ('productdescription', models.TextField()),
                ('productcategory', models.IntegerField()),
                ('reorderpoint', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=100)),
                ('images', models.JSONField()),
                ('createduser', models.CharField(max_length=100)),
                ('modifieduser', models.CharField(max_length=100)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('rowstatus', models.BooleanField(default=True)),
            ],
        ),
        
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouseid', models.AutoField(primary_key=True, serialize=False)),
                ('warehousename', models.CharField(max_length=255)),
                ('createduser', models.CharField(max_length=100)),
                ('modifieduser', models.CharField(max_length=100)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('rowstatus', models.BooleanField(default=True)),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idscore.location')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryid', models.AutoField(primary_key=True, serialize=False)),
                ('quantityavailable', models.CharField(max_length=50)),
                ('minstocklevel', models.CharField(max_length=50)),
                ('maxstocklevel', models.CharField(max_length=50)),
                ('reorderpoint', models.IntegerField()),
                ('createduser', models.CharField(max_length=100)),
                ('modifieduser', models.CharField(max_length=100)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('rowstatus', models.BooleanField(default=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idscore.product')),
                ('warehouseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idscore.warehouse')),
            ],
        ),
         migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchid', models.AutoField(primary_key=True)),
                ('productid', models.ForeignKey(on_delete=models.CASCADE, to='idscore.Product', default=1)),  # Adjust default value accordingly
                ('manufacturedate', models.DateField()),
                ('expirydate', models.DateField()),
                ('quantity', models.CharField(max_length=100)),
                ('createduser', models.CharField(max_length=100)),
                ('modifieduser', models.CharField(max_length=100)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('rowstatus', models.BooleanField(default=True)),
            ],
         ),
    ]
