# Generated by Django 5.0.6 on 2024-07-05 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0002_alter_batch_batchid_alter_batch_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idscore.product'),
        ),
    ]
