# Generated by Django 5.0.6 on 2024-07-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0003_alter_batch_productid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
