# Generated by Django 5.0.6 on 2024-07-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0004_delete_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchid', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturedate', models.DateField()),
                ('expirydate', models.DateField()),
                ('quantity', models.CharField()),
                ('createduser', models.CharField(max_length=100)),
                ('modifieduser', models.CharField(max_length=100)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('rowstatus', models.BooleanField(default=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idscore.product')),
            ],
        ),
    ]
