# Generated by Django 5.0.6 on 2024-07-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0006_placement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Placement',
        ),
    ]
