# Generated by Django 5.0.6 on 2024-07-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0007_delete_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('placementId', models.AutoField(primary_key=True, serialize=False)),
                ('aile', models.CharField(max_length=50)),
                ('bin', models.CharField(max_length=50)),
                ('createduser', models.CharField(max_length=100)),
                ('modifieduser', models.CharField(max_length=100)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('rowstatus', models.BooleanField(default=True)),
                ('batchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idscore.batch')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idscore.product')),
                ('warehouseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idscore.warehouse')),
            ],
        ),
    ]
