# Generated by Django 5.0.6 on 2024-07-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0008_placement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='reorderpoint',
            new_name='catreorderpoint',
        ),
    ]
