# Generated by Django 5.0.6 on 2024-07-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0009_rename_reorderpoint_inventory_catreorderpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='catreorderpoint',
            new_name='invreorderpoint',
        ),
    ]
