# Generated by Django 5.0.6 on 2024-07-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0011_alter_batch_expirydate_alter_batch_manufacturedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='manufacturedate',
            field=models.DateField(null=True),
        ),
    ]
