# Generated by Django 5.0.6 on 2024-07-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0012_alter_batch_manufacturedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='invreorderpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
