# Generated by Django 5.0.6 on 2024-07-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0014_deleterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='approverId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
