# Generated by Django 5.0.6 on 2024-07-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0015_alter_deleterequest_approverid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleterequest',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
