# Generated by Django 5.0.6 on 2024-07-12 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0016_deleterequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestProduct',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('approvedManagerId', models.IntegerField(blank=True, null=True)),
                ('approvedAdminId', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idscore.product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
