# Generated by Django 5.0.6 on 2024-07-12 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0017_requestproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('featureId', models.AutoField(primary_key=True, serialize=False)),
                ('stock_control', models.BooleanField(default=False)),
                ('override_manager_approval', models.BooleanField(default=False)),
                ('view_product_details', models.BooleanField(default=False)),
                ('update_stock', models.BooleanField(default=False)),
                ('delete_product', models.BooleanField(default=False)),
                ('image_search', models.BooleanField(default=False)),
                ('qr_scan', models.BooleanField(default=False)),
                ('qr_generation', models.BooleanField(default=False)),
                ('add_product', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
                ('request_product', models.BooleanField(default=False)),
                ('notifications', models.BooleanField(default=False)),
                ('raise_request', models.BooleanField(default=False)),
                ('low_stock_items', models.BooleanField(default=False)),
                ('expiry_date_items', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
