# Generated by Django 5.0.6 on 2024-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0018_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='batchid',
        ),
        migrations.AddField(
            model_name='placement',
            name='expirydate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='manufacturedate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='quantity',
            field=models.CharField(default=0),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
