# Generated by Django 5.0.6 on 2024-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0019_remove_placement_batchid_placement_expirydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='quantity',
            field=models.CharField(),
        ),
    ]
