# Generated by Django 5.0.6 on 2024-07-12 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0021_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='batchid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idscore.batch'),
        ),
    ]
