# Generated by Django 5.0.6 on 2024-07-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0023_alter_placement_batchid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='expirydate',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='manufacturedate',
        ),
    ]
