# Generated by Django 5.0.6 on 2024-07-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0024_remove_placement_expirydate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='quantity',
        ),
    ]
