# Generated by Django 5.0.6 on 2024-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0028_remove_batch_quantity_placement_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='quantity',
            field=models.CharField(),
        ),
    ]
