# Generated by Django 5.0.6 on 2024-07-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0031_alter_batch_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='quantity',
            new_name='placementQuantity',
        ),
    ]
