# Generated by Django 5.0.6 on 2024-07-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0033_alter_inventory_maxstocklevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='placementQuantity',
            field=models.IntegerField(),
        ),
    ]
