# Generated by Django 5.0.6 on 2024-07-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0034_alter_placement_placementquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantityavailable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
